name: cs2109s-ay2223s1
channels:
  - conda-forge
  - pytorch
dependencies:
  - matplotlib=3.5.2
  - notebook=6.4.12
  - numpy=1.21.5
  - python=3.9.9
  - pandas=1.5.2
  - scikit-learn=1.0.2
  - seaborn=0.12.0
  - timeout-decorator=0.5.0
  - pytorch=1.11.0
  - torchvision=0.12.0